services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node-backend
        environment:
        - NODE_ENV=development
        - MONGO_URI=${MONGODB_URI}
        ports:
        - "${PORT}:${PORT}"
        depends_on:
        - mongo
        networks:
        - app-network

    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
        - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
        volumes:
        - mongo-data:/data/db
        networks:
        - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
